//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlUpgrade.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ControlUpgrade.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application must be run as Administrator..
        /// </summary>
        internal static string AdminWarning {
            get {
                return ResourceManager.GetString("AdminWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Privileges.
        /// </summary>
        internal static string AdminWarningTitle {
            get {
                return ResourceManager.GetString("AdminWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Mode.
        /// </summary>
        internal static string DarkModeToggle {
            get {
                return ResourceManager.GetString("DarkModeToggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error locking upgrade: {0}.
        /// </summary>
        internal static string ErrorLocking {
            get {
                return ResourceManager.GetString("ErrorLocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading registry: {0}.
        /// </summary>
        internal static string ErrorReadingRegistry {
            get {
                return ResourceManager.GetString("ErrorReadingRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error unlocking upgrade: {0}.
        /// </summary>
        internal static string ErrorUnlocking {
            get {
                return ResourceManager.GetString("ErrorUnlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the current Windows version..
        /// </summary>
        internal static string ErrorWinVersion {
            get {
                return ResourceManager.GetString("ErrorWinVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔒 Lock Upgrade.
        /// </summary>
        internal static string LockButton {
            get {
                return ResourceManager.GetString("LockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No values found in registry key..
        /// </summary>
        internal static string NoRegistryValues {
            get {
                return ResourceManager.GetString("NoRegistryValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 📂 Open in Registry Editor.
        /// </summary>
        internal static string OpenRegistryEditorButton {
            get {
                return ResourceManager.GetString("OpenRegistryEditorButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Key Values:.
        /// </summary>
        internal static string RegistryKeyLabel {
            get {
                return ResourceManager.GetString("RegistryKeyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry key not found..
        /// </summary>
        internal static string RegistryKeyNotFound {
            get {
                return ResourceManager.GetString("RegistryKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registry Info.
        /// </summary>
        internal static string RegistryTabHeader {
            get {
                return ResourceManager.GetString("RegistryTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade is currently locked..
        /// </summary>
        internal static string StatusLocked {
            get {
                return ResourceManager.GetString("StatusLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade is currently unlocked..
        /// </summary>
        internal static string StatusUnlocked {
            get {
                return ResourceManager.GetString("StatusUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string SuccessTitle {
            get {
                return ResourceManager.GetString("SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Upgrade Control.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔓 Unlock Upgrade.
        /// </summary>
        internal static string UnlockButton {
            get {
                return ResourceManager.GetString("UnlockButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade Control.
        /// </summary>
        internal static string UpgradeGroupHeader {
            get {
                return ResourceManager.GetString("UpgradeGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade locked to {0}..
        /// </summary>
        internal static string UpgradeLockedMessage {
            get {
                return ResourceManager.GetString("UpgradeLockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade unlocked..
        /// </summary>
        internal static string UpgradeUnlockedMessage {
            get {
                return ResourceManager.GetString("UpgradeUnlockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows Version:.
        /// </summary>
        internal static string VersionLabel {
            get {
                return ResourceManager.GetString("VersionLabel", resourceCulture);
            }
        }
    }
}
